name: balanceo_atm_bna
description: MVP offline para balanceo de ATM con OCR on-device y PDF.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.4.0
  pdf: ^3.11.1
  printing: ^5.13.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
